# Generated by Django 2.0.6 on 2018-08-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0003_auto_20180811_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nosotros',
            name='columna_dos',
        ),
    ]
