# Generated by Django 2.0.6 on 2018-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0004_remove_nosotros_columna_dos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosotros',
            old_name='descripcion',
            new_name='descripcion_columna1',
        ),
        migrations.AddField(
            model_name='nosotros',
            name='descripcion_columna2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
