# Generated by Django 2.0.6 on 2018-07-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('coordenadas', models.URLField()),
            ],
        ),
    ]
