# Generated by Django 2.0.6 on 2018-07-26 14:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0002_auto_20180720_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionMapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.CharField(max_length=100)),
                ('rif', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Maximo 15 digitos.', regex='^\\d{7,15}$')])),
                ('fax', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Maximo 15 digitos.', regex='^\\d{7,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
