# Generated by Django 2.0.6 on 2018-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0004_auto_20180726_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionmapa',
            options={'verbose_name_plural': 'Ubicaciones en el mapa'},
        ),
        migrations.AddField(
            model_name='ubicacionmapa',
            name='nit',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
