# Generated by Django 2.0.6 on 2018-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0005_auto_20180726_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
