# Generated by Django 2.0.6 on 2018-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0006_auto_20180726_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='rif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionmapa',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
