# Generated by Django 2.0.6 on 2018-07-26 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0007_auto_20180726_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbicacionMapa',
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicaciones', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='coordenadas',
            new_name='mapa_url',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='telefono',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='x_coord',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Coordenada X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='y_coord',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Coordenada X'),
            preserve_default=False,
        ),
    ]
