# Generated by Django 2.0.6 on 2018-08-14 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donde_estamos', '0008_auto_20180726_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='x_coord',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Coordenada X'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='y_coord',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Coordenada X'),
        ),
    ]
