"""
Django settings for pandock project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .settings import *

DEBUG = False

ALLOWED_HOSTS =  [
    '145.239.119.232',
    'pandock.com',
    'http://145.239.119.232',
    'http://pandock.com/',
    'www.pandock.com',
    'http://www.pandock.com/',
    'web.pandock.com',
    'http://web.pandock.com/',
]

HOST = 'www.pandock.com/'

LANGUAGE_CODE = 'es-ve'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets/')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

GOOGLE_ANALYTICS = {
    'google_analytics_id': 'UA-157130886-1',
}
