# Generated by Django 2.0.6 on 2018-07-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
