# Generated by Django 2.0.6 on 2018-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='posicion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2),
        ),
    ]
