# Generated by Django 2.0.6 on 2018-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180720_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='posicion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
