# Generated by Django 2.0.6 on 2018-07-28 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180726_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='posicion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='posicion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
