# Generated by Django 2.0.6 on 2018-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180802_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='../static/img/logo.png', null=True, upload_to='productos/producto', verbose_name='Imagen (logo por default)'),
        ),
    ]
