# Generated by Django 2.0.6 on 2018-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20180802_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['titulo']},
        ),
    ]
