# Generated by Django 2.0.6 on 2018-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20180811_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='../assets/img/logo.png', null=True, upload_to='productos/producto', verbose_name='Imagen (logo por default)'),
        ),
    ]
