# Generated by Django 2.0.6 on 2018-08-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20180811_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='../assets/img/logo.png', upload_to='productos/producto', verbose_name='Imagen (logo por default)'),
        ),
    ]
