# Generated by Django 2.2.9 on 2020-04-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='archivo_publicado',
            field=models.BooleanField(default=True),
        ),
    ]
