# Generated by Django 2.0.6 on 2018-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20180831_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
