# Generated by Django 2.0.6 on 2018-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='slug',
            field=models.SlugField(default='crema-chantilly', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
