# Generated by Django 2.0.6 on 2018-08-11 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20180803_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
