# Generated by Django 2.0.6 on 2018-08-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_categoria_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden']},
        ),
    ]
