# Generated by Django 2.0.6 on 2018-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_receta_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='slider_display',
            field=models.BooleanField(default=False, verbose_name='Mostrar en slider home'),
        ),
    ]
